FROM mysql:5.6.35
COPY ./single_file.sql /docker-entrypoint-initdb.d
#docker run --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=dol -d dolmysql --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=1